### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by Qengineering**

### CODE REVIEW

**Comment by scangit** [comment]
There is no memory leak here, real_seg_mask is freed in main. ( free(seg_mask); )

**Comment by Qengineering** [comment]
On which line in main.cc?
I don't want to complain, but the memory consumption of the CPP examples really increased evenly.

**Comment by airockchip** [comment]
https://github.com/airockchip/rknn_model_zoo/blob/main/examples/yolov5_seg/cpp/main.cc#L119

**Comment by Qengineering** [comment]
Sorry, we're not talking about seg_mask, but **real_seg_mask** in `rknpu1/postprocess.cc` or `rknpu2/postprocess.cc`
```cpp
    uint8_t *real_seg_mask = (uint8_t *)malloc(ori_in_height * ori_in_width * sizeof(uint8_t));
    seg_reverse(all_mask_in_one, cropped_seg_mask, real_seg_mask,
                model_in_height, model_in_width, cropped_height, cropped_width, ori_in_height, ori_in_width, y_pad, x_pad);
    od_results->results_seg[0].seg_mask = real_seg_mask;
    free(all_mask_in_one);
    free(cropped_seg_mask);
    free(seg_mask);
```
It should be freed in the series at the end.
```cpp
    free(all_mask_in_one);
    free(cropped_seg_mask);
    free(real_seg_mask);   <<<--------------------
    free(seg_mask);
```

**Pull request closed without merging**
